version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: 'wpapp'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    container_name: wp_docker_db
    restart: always
    ports: 
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'wpapp_db'
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "12345"
      MYSQL_ROOT_PASSWORD: "12345"
    volumes:
      - ./db:/var/lib/mysql
      - ./db.sql:/db.sql